name: CD

on:
  push:
    branches: 
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      run: |
        sudo apt-get update
        sudo apt-get install hugo -y
        rm -rf public/
        python3 --version
        pip3 install awscli --upgrade --user
        # aws s3 sync