name: CD

on:
  push:
    branches: 
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      run: |
        curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest \
        | grep  browser_download_url \
        | grep Linux-64bit.deb \
        | grep -v extended \
        | cut -d '"' -f 4 \
        | wget -i -

        sudo dpkg -i hugo*_Linux-64bit.deb
        rm -rf public/
        hugo version
        hugo
        pip3 install wheel
        pip3 install --upgrade setuptools
        pip3 install awscli --upgrade --user
        sudo pip install Pygments
        aws s3 sync public/ s3://${{ secrets.S3_BUCKET_NAME }} --acl public-read --delete
        aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*'